server:
  port: 8888

spring:
  profiles:
    active: vault
  application:
    name: configserver
  cloud:
    config:
      server:
#        native:
#          searchLocations: file://${user.home}/config-repo
#        git:
#          uri: https://github.com/weekly-drafts/config-repo-spring-cloud-configserver-vault
        vault:
          port: 8200
          host: 127.0.01
          scheme: http
          authentication: TOKEN
#          token: myroot
          kv-version: 2